### ISSUE TITLE
How to make the victim run it?

### ISSUE THREAD

**Issue by YESY208** [AstraaDev/Discord-Token-Grabber#11]

**Comment by scratchusernamemrtbts** [comment]
Just send the code to the victim pc and tell him how to run python

**Comment by Kayz1nn** [comment]
convert .py in .exe with auto-py-exe script

**Comment by R1DF** [comment]
Since this is just the code of the token grabber, you'll need the target to have Python installed and have them run the code. Chances are, it will probably seem suspicious to them and they'll refuse.

**Comment by Manhajus-Salafiyyah** [comment]
make it an exe file via pyinstaller and use stenography in order to disguise the exe file as an image. Preferably an image that is blank to make it seem it hasnt loaded, and tell victim to download it. More likely for them to download the image then, whilst the exe file executes in background

**Comment by scratchusernamemrtbts** [comment]
> make it an exe file via pyinstaller and use stenography in order to disguise the exe file as an image. Preferably an image that is blank to make it seem it hasnt loaded, and tell victim to download it. More likely for them to download the image then, whilst the exe file executes in background

I somehow cant get pyinstaller to work but thanks for the disguise method
(I literally told my friend that the file is a learning resource (which technichally it is cus it help him know that u shouldn’t open random .py files) and then he ran it and i trolled him making him swear in my server)

**Comment by scratchusernamemrtbts** [comment]
> make it an exe file via pyinstaller and use stenography in order to disguise the exe file as an image. Preferably an image that is blank to make it seem it hasnt loaded, and tell victim to download it. More likely for them to download the image then, whilst the exe file executes in background

I somehow cant get pyinstaller to work but thanks for the disguise method
(I literally told my friend that the file is a learning resource (which technichally it is cus it help him know that u shouldn’t open random .py files) and then he ran it and i trolled him making him swear in my server)

**Comment by scratchusernamemrtbts** [comment]
Wth why it commented 2
