### ISSUE TITLE
Script won't run. 

### ISSUE THREAD

**Issue by Matte2322** [AstraaDev/Discord-Token-Grabber#17]
I don't know if it just me, but this part of the code "if os.name != 'nt': exit()", doesn't execute the entire script. I was using it for testing purposes by the way. Do you know why you've added that to your code? I'm curious to know why. Let me know if you have an answer and take your time.

**Comment by gabe-1971** [comment]
For me, the issue is at line 43 "        for line in [x.strip() for x in open(f"{path}\\{file_name}", errors="ignore").readlines() if x.strip()]:"
This gives me a syntax error. Anyone know why?

**Comment by iluvcatz** [comment]
> I don't know if it just me, but this part of the code "if os.name != 'nt': exit()", doesn't execute the entire script. I was using it for testing purposes by the way. Do you know why you've added that to your code? I'm curious to know why. Let me know if you have an answer and take your time. 

it might be because you aren't on windows?

**Comment by Matte2322** [comment]
> > I don't know if it just me, but this part of the code "if os.name != 'nt': exit()", doesn't execute the entire script. I was using it for testing purposes by the way. Do you know why you've added that to your code? I'm curious to know why. Let me know if you have an answer and take your time.
> 
> it might be because you aren't on windows?

Correct, I use Arch Linux btw as my daily driver.
