### ISSUE TITLE
Replit? or do i need another python app

### ISSUE THREAD

**Issue by Kmeha** [AstraaDev/Discord-Token-Grabber#21]
everytime i run it it says "replit died unexpectedly"

**Comment by 0xMichael** [comment]
I don't see why you would want to run this script in replit?

The script needs to be on a machine with discord etc on it to retrieve any tokens.

**Comment by FollowToS** [comment]
Where can I find a replit token logger?

**Comment by riso38** [comment]
write on instagram seve.services for working grabber

**Comment by KingKrex69** [comment]
> Where can I find a replit token logger?

you cant

**Comment by Joshua11TheHacker** [comment]
bro this issues section is so dumb wtf
