### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 6monthpeek** [AstraaDev/Discord-Token-Grabber#23]
I changed the WEBHOOK URL at line 184. Then I ran it "python token_grabber.py" I saw the cmd screen but webhook didn't send anything.

**Comment by YokelMan** [comment]
I assume you mean the "WEBHOOK_URL" string from line 185.

Have you configured the webhook properly? Make sure you have selected the channel to which it sends correctly.
![An image showing channel option in webhook settings](https://user-images.githubusercontent.com/52625714/170867407-d1bd40e0-26a0-4af2-ab55-2b1568f7dc75.png)

Also make sure you have copied and pasted the webhook URL properly. It might just happen that you miss quotation marks either at the start or end of the webhook when replacing "WEBHOOK_URL" from the program.
