### ISSUE TITLE
Nothing shows up when I run it

### ISSUE THREAD

**Issue by UwUbobo1973** [AstraaDev/Discord-Token-Grabber#41]
When i run it, I will not get a Discord message and i put the webhook in the right place. Can someone help me.
![Unbenannt](https://user-images.githubusercontent.com/116450903/205009922-c84ba70d-ad13-4c7a-997a-5b7eec327b64.PNG)

**Comment by jven123** [comment]
its outdated go find a new one in astraa repo

**Comment by UwUbobo1973** [comment]
thanks
